export const ActionTypes = {
  MOVIE_LOADING: "MOVIE_LOADING",
  MOVIE_SUCCESS: "MOVIE_SUCCESS",
  MOVIE_ERROR: "MOVIE_ERROR",
  GENRES_LOADING: "GENRES_LOADING",
  GENRES_SUCCESS: "GENRES_SUCCESS",
  GENRES_ERROR: "GENRES_ERROR",
};
